spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ali47:3306/jstock?allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: lenovo.112
  jpa:
    hibernate:
      ddl-auto: create   # 第一次建表用create,之后用update，
    show-sql: false    # 在控制台打印出sql语句
server:
  port: 8081
  servlet:
    context-path: /jstock